### ISSUE TITLE
Help with debounce cancellation

### ISSUE THREAD

**Issue by diamondfish** [slorber/awesome-debounce-promise#21] opened 2021-10-26 14:33 UTC
Maybe this isn't the place to ask for help, but I'm struggling with how to implement `awesome-imperative-promise`, and hopefully someone can help me here. My code looks something like this:

```jsx
const MyComponent = ({ doStuff }) => {
  const [value, setValue] = React.useState('');

  const debouncedDoStuff = useConstant(() =>
    AwesomeDebouncePromise(doStuff , 500)
  );

  const onChange = React.useCallback(
    (event) => {
      setValue(event.target.value);
      debouncedDoStuff(event.target.value);
    },
    [debouncedDoStuff]
  );

  const onKeyDown = (e) => {
    if (e.key === 'Enter' && e.shiftKey === false) {
      // Cancel the possibly active debounce promise here.
      // Then continue with the ordinary doStuff-function.
      doStuff(event.target.value);
    }
  };

return (
    <TextInput
        value={value}
        onChange={onChange}
        onKeyDown={onKeyDown}
        // ...
    />
  )
}
```

I think I got everything that I use in my code in the example and that my example makes sense. Basically I have a text input field that acts like a search field. When the input field changes, the `doStuff`-function is called with a debounce. Whenever the user presses `Enter`, I want the current debounce promise to be cancelled, and perform the `doStuff`-function without input lag.

How can I implement this using `awesome-imperative-promise`?

**Comment by slorber** [comment] 2021-10-28 08:34
Issues are not for support sorry.

I don't think the current abstractions are good for your use-case, duplicate of https://github.com/slorber/awesome-debounce-promise/issues/3

**Closed as completed by slorber** 2021-10-28 08:34 UTC
